-- Bola Burger — schema completo para rodar no SQL Editor do Supabase
-- (Dashboard → SQL → New query → colar e executar)

create table public.pedidos (
  id bigint generated by default as identity primary key,
  cliente text not null,
  telefone text,
  endereco text,
  itens jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null default 0,
  status text not null default 'pendente',
  created_at timestamptz not null default now(),
  tipo_entrega text not null default 'retirada',
  taxa_entrega numeric not null default 0,
  forma_pagamento text not null default 'dinheiro',
  pago boolean not null default false
);

grant select, insert, update, delete on public.pedidos to anon, authenticated;
grant all on public.pedidos to service_role;
grant usage, select on sequence public.pedidos_id_seq to anon, authenticated;

alter table public.pedidos enable row level security;

create policy "pedidos_public_all" on public.pedidos
  for all to anon, authenticated using (true) with check (true);

alter table public.pedidos replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'pedidos'
  ) then
    execute 'alter publication supabase_realtime add table public.pedidos';
  end if;
end $$;

-- Fechamentos diários (encerrar dia + histórico + relatórios)
create table if not exists public.fechamentos_diarios (
  id bigint generated by default as identity primary key,
  data date not null,
  faturado numeric(10,2) not null default 0,
  recebido numeric(10,2) not null default 0,
  a_receber numeric(10,2) not null default 0,
  total_pedidos int not null default 0,
  pedidos_entregues int not null default 0,
  pedidos_cancelados int not null default 0,
  detalhes jsonb not null default '[]'::jsonb,
  turno_id bigint,
  iniciado_em timestamptz,
  encerrado_em timestamptz,
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.fechamentos_diarios to anon, authenticated;
grant all on public.fechamentos_diarios to service_role;
grant usage, select on sequence public.fechamentos_diarios_id_seq to anon, authenticated;

alter table public.fechamentos_diarios enable row level security;

create policy "fechamentos_public_all" on public.fechamentos_diarios
  for all to anon, authenticated using (true) with check (true);

-- Turnos (iniciar / encerrar dia manualmente)
create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  iniciado_em timestamptz not null default now(),
  encerrado_em timestamptz
);

grant select, insert, update, delete on public.turnos to anon, authenticated;
grant all on public.turnos to service_role;
grant usage, select on sequence public.turnos_id_seq to anon, authenticated;

alter table public.turnos enable row level security;

create policy "turnos_public_all" on public.turnos
  for all to anon, authenticated using (true) with check (true);
