
create table public.pedidos (
  id bigint generated by default as identity primary key,
  cliente text not null,
  telefone text,
  endereco text,
  itens jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null default 0,
  status text not null default 'pendente',
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.pedidos to anon, authenticated;
grant all on public.pedidos to service_role;
grant usage, select on sequence public.pedidos_id_seq to anon, authenticated;

alter table public.pedidos enable row level security;

create policy "pedidos_public_all" on public.pedidos
  for all to anon, authenticated using (true) with check (true);
