-- Fechamentos diários — rode no SQL Editor se o projeto já existia antes desta feature

create table if not exists public.fechamentos_diarios (
  id bigint generated by default as identity primary key,
  data date not null unique,
  faturado numeric(10,2) not null default 0,
  recebido numeric(10,2) not null default 0,
  a_receber numeric(10,2) not null default 0,
  total_pedidos int not null default 0,
  pedidos_entregues int not null default 0,
  pedidos_cancelados int not null default 0,
  detalhes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.fechamentos_diarios to anon, authenticated;
grant all on public.fechamentos_diarios to service_role;
grant usage, select on sequence public.fechamentos_diarios_id_seq to anon, authenticated;

alter table public.fechamentos_diarios enable row level security;

drop policy if exists "fechamentos_public_all" on public.fechamentos_diarios;
create policy "fechamentos_public_all" on public.fechamentos_diarios
  for all to anon, authenticated using (true) with check (true);
