-- Turnos operacionais — iniciar/encerrar dia manualmente

create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  iniciado_em timestamptz not null default now(),
  encerrado_em timestamptz
);

grant select, insert, update, delete on public.turnos to anon, authenticated;
grant all on public.turnos to service_role;
grant usage, select on sequence public.turnos_id_seq to anon, authenticated;

alter table public.turnos enable row level security;

drop policy if exists "turnos_public_all" on public.turnos;
create policy "turnos_public_all" on public.turnos
  for all to anon, authenticated using (true) with check (true);

-- Permite vários fechamentos no mesmo dia (vários turnos)
alter table public.fechamentos_diarios
  drop constraint if exists fechamentos_diarios_data_key;

alter table public.fechamentos_diarios
  add column if not exists turno_id bigint references public.turnos(id),
  add column if not exists iniciado_em timestamptz,
  add column if not exists encerrado_em timestamptz;
